# 1. Usar a imagem oficial com o plugin de management pré-instalado
FROM rabbitmq:3.13-management

# 2. Definir o diretório de trabalho para configurações
WORKDIR /etc/rabbitmq

EXPOSE 5672 15672

# 6. Comando para iniciar o servidor
CMD ["rabbitmq-server"]