name: Smart Deploy

on:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Define as saídas para os próximos jobs
    outputs:
      keycloak: ${{ steps.filter.outputs.keycloak }}
      rabbitmq: ${{ steps.filter.outputs.rabbitmq }}
      prometheus: ${{ steps.filter.outputs.prometheus }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            keycloak:
              - 'keycloak/**'
            rabbitmq:
              - 'rabbitmq/**'
            prometheus:
              - 'prometheus/**'

  deploy-keycloak:
    needs: changes
    if: ${{ needs.changes.outputs.keycloak == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Easypanel Keycloak
        run: curl -X POST "${{ secrets.EASYPANEL_KEYCLOAK_WEBHOOK }}"

  deploy-rabbitmq:
    needs: changes
    if: ${{ needs.changes.outputs.rabbitmq == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Easypanel RabbitMQ
        run: curl -X POST "${{ secrets.EASYPANEL_RABBITMQ_WEBHOOK }}"

  deploy-prometheus:
    needs: changes
    if: ${{ needs.changes.outputs.prometheus== 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Easypanel Prometheus
        run: curl -X POST "${{ secrets.EASYPANEL_PROMETHEUS_WEBHOOK }}"